### PR TITLE
Adding intro in static site generators

### PR DESCRIPTION
**Pull request by spekulatius**
Hello @asleepysamurai   

just adding some more information in by sharing an intro in static site generators

Cheers!

### CODE REVIEW

**Comment by asleepysamurai** [comment]
Anybody who is persistent enough to find YASS-Gen amongst the sea of other (better) static site generators, definitely already knows what a static site generator is. 

In addition as pointed out by @Sirikon, this seems to be a blatant attempt at pushing your blog, which I'm not really all that inclined to support. I'd suggest posting future articles to Hacker News, /r/programming, and dev.to instead of polluting Github projects with unnecessary pull requests.

**Comment by spekulatius** [comment]
You are rightfully denying the PR. After reading Sirikon post I understand this isn't nice :/ I'm just a coder trying to learn some marketing basics. Again: sorry, it won't happen again. Good luck with your project!

**Comment by asleepysamurai** [comment]
@spekulatius That's totally understandable. It can be difficult to get people to read your articles when you're initially starting out. This is why I have made some suggestions for places you can use to promote your articles. Github just isn't one of them. Thanks for understanding and good luck with your blog and your learning :)

**Comment by spekulatius** [comment]
Yeah @asleepysamurai, I'll give these a try. Thank you for your understanding 🙏️

**Pull request closed without merging**
